In [60]:
import pandas as pd

In [61]:
x = pd.read_csv("AgeFilled.csv")

In [62]:
x['Designation'].unique()
x.head()

,Employee Code,Employee_Name,Interim Manager,Band,Department,Designation,Process,Education Field,Gender,Age,Salary
0,455447,LJBTYYQM EBQNHPFG,SKTEGGQ NIIMGJE,A2,MT,Analyst,Finance,Commerce,Male,23,NaN
1,431659,KLBMBMFY KQUUUEJN,QEHHGEG DAGIGMJ,A3,MT,Analyst,Underpayments,Medical,Male,45,NaN
2,508065,ZJKQOSHS AQEBHMAF,FYAJPZC DJCSMNF,A2,PFS 2,BPQA,Underpayments,Arts,Male,37,NaN
3,581649,RBYOTBBX YEILAUJM,GTRTPJQ RXCOHVN,A2,PFS 1,Senior Analyst,Underpayments,Technical,Female,28,NaN
4,588863,XYRANZYP DPWOXGFF,WGKGXQL QDCXTCZ,A3,FCC,Analyst,Quality,Commerce,Female,30,NaN

In [63]:
#Salary Module
#p2 band: exec_asst, manager, team lead
#very high*0.7, high*0.3
import random
salary_p2 = ['Very High','Very High','Very High','Very High','Very High','Very High','Very High','High','High','High']

for i in range(0,3000):
    if x['Band'][i] == "P2":
        print(x['Band'][i])
        if x['Designation'][i] == "Executive Assistant" or x['Designation'][i]=="Team Lead" or x['Designation'][i]== "Manager":
            x['Salary'][i] = random.choice(salary_p2)
        x.to_csv(r'Check_this.csv')

P2
P2
P2
P2
P2
P2
P2
P2
P2
P2
P2
P2
P2
P2

C:\Users\USER\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

P2
P2
P2
P2
P2
P2
P2
P2
P2
P2
P2
P2
P2
P2
P2
P2

In [64]:
high=0
very_high = 0
for i in range(0,3000):
    if x['Band'][i] == "P2":
        if x['Salary'][i] == "High":
            high = high + 1
        else:
            very_high = very_high + 1
print(very_high,high)

22 8

In [65]:
#Manipulating P1 band
# Very High, High!
#Probabilities
#1 manag,team_l,b_a == 0.5-0.5
# others = v.h =0.2
salary_p11 =['Very High','High']
for i in range(0,3000):
    if x['Band'][i] == "P1":
        if (x['Designation'][i] == "Business Analyst" or x['Designation'][i]=="Team Lead" or x['Designation'][i]== "Manager"):
            print(x['Designation'])
            x['Salary'][i] = random.choice(salary_p11)



salary_p1 =['Very High','Very High','High','High','High','High','High','High','High','High']
for i in range(0,3000):
    if x['Band'][i] == "P1":
        if (x['Designation'][i] == "Coding Analyst" or x['Designation'][i]=="Analyst" or x['Designation'][i]== "Senior Analyst"):

            x['Salary'][i] = random.choice(salary_p1)
x.to_csv(r'CheckThis2.csv')

0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object

C:\Users\USER\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\USER\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [66]:
high=0
very_high = 0
for i in range(0,3000):
    if x['Band'][i] == "P1":
        high = high + 1
        print(x['Designation'])
print(high)

0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
0                   Analyst
1                   Analyst
2                      BPQA
3            Senior Analyst
4                   Analyst
               ...
2995         Coding Analyst
2996                Analyst
2997         Senior Analyst
2998    Executive Assistant
2999             Consultant
Name: Designation, Length: 3000, dtype: object
20

In [67]:
salary_p1 =['Very High','Very High','High','High','High','High','High','High','High','High']
for i in range(0,3000):
    if x['Band'][i] == "P1":
        if (x['Designation'][i] == "Coding Analyst" or x['Designation'][i]=="Analyst" or x['Designation'][i]== "Senior Analyst"):

            x['Salary'][i] = random.choice(salary_p1)
x.to_csv(r'CheckThis2.csv')

C:\Users\USER\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [72]:
#Manipulating Manager band
# Good, High!
#Probabilities
#manager == 0.5-0.5
#exec manager= h =0.2

salary_ma =['Good','High']
for i in range(0,3000):
    if x['Band'][i] == "Manager":
        if (x['Designation'][i]== "Manager"):
            x['Salary'][i] = random.choice(salary_ma)

salary_ma1 =['Good','Good','Good','Good','Good','Good','Good','Good','Good','High','High']
for i in range(0,3000):
    if x['Band'][i] == "Manager":
        if (x['Designation'][i]== "Executive"):
            x['Salary'][i] = random.choice(salary_ma1)
            
x.to_csv(r'CheckThis3.csv')

C:\Users\USER\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\USER\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [77]:
#Manipulating A3 band
# Good
#Probabilities
#all are having good salary

salary_a3 =['Good']
for i in range(0,3000):
    if x['Band'][i] == "A3":
        x['Salary'][i] = random.choice(salary_a3)
        
x.to_csv(r'CheckThis4.csv')

C:\Users\USER\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [86]:
#Manipulating A2 band
# Good, fair
#Probabilities


salary_a2 =['Good','Good',"Fair","Fair","Fair","Fair","Fair","Fair","Fair","Fair"]
for i in range(0,3000):
    if x['Band'][i] == "A2":
        if (x['Designation'][i]== "Analyst"):
            x['Salary'][i] = random.choice(salary_a2)
            
salary_a21 =['Good','Good','Good','Good','Good','Good','Good',"Fair","Fair","Fair"]
for i in range(0,3000):
    if x['Band'][i] == "A2":
        if (x['Designation'][i]== "Coding Analyst" or x['Designation'][i]== "Senior Analyst" or x['Designation'][i]== "MT/QA" or x['Designation'][i]== "Business Analyst"):
            x['Salary'][i] = random.choice(salary_a21)
            
salary_a22 =['Good','Good','Good','Good','Good','Good',"Fair","Fair","Fair","Fair"]
for i in range(0,3000):
    if x['Band'][i] == "A2":
        if (x['Designation'][i]== "BPQA" or x['Designation'][i]== "Consultant" or x['Designation'][i]== "Support" or x['Designation'][i]== "SD Agent" or x['Designation'][i]== "Engineer" or x['Designation'][i]== "Executive"):
            x['Salary'][i] = random.choice(salary_a22)
        
x.to_csv(r'CheckThis5.csv')

C:\Users\USER\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\USER\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\USER\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [87]:
#Manipulating A1 band
# Good 0.3, Fair 0.7
#Probabilities

salary_a1 =['Good','Good','Good',"Fair","Fair","Fair","Fair","Fair","Fair","Fair"]
for i in range(0,3000):
    if x['Band'][i] == "A1":
        x['Salary'][i] = random.choice(salary_a1)
        
x.to_csv(r'Final_salary_data.csv')

C:\Users\USER\Anaconda3.1\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [89]:
len(x['Process'].unique())

77